#!/bin/sh

KEY=/etc/openssl/private/slyde.priv.key
PASS=pass:slyde

if [ -f ${SRC} ] ; then

	openssl rsautl -decrypt -inkey ${KEY} -passin ${PASS} -in ${SRC} -out ${DST}

	if [ -f ${DST} ]
	then
		return 0
	fi
fi

return 1

