#!/bin/sh

log_msg() {
	BOLD="\e[1m"
	NORMAL="\e[0m"
	NBCOLS=80
	MSG="$1"
	COL=$(($NBCOLS-${#MSG}+5))

	SCRIPT=$2

	echo -n $MSG
	
	if [ ! -x $SCRIPT ]
	then
		printf $BOLD"%${COL}s"$NORMAL  "[FAIL]"
		echo ""
		return 1
	else
		$SCRIPT
		
		if [ $? -eq 0 ]
		then
			printf $BOLD"%${COL}s"$NORMAL  "[OK]"
			echo ""
			return 0
		else
			printf $BOLD"%${COL}s"$NORMAL  "[KO]"
			echo ""
			return 1
		fi
	fi

}

